### PR TITLE
Forward errors to clones (fixes #1)

### LINKED ISSUE #1: Swallows errors
The use of [pump](https://github.com/mafintosh/pump) means errors on the source stream won't be re-emitted on the cloneable stream, or on clones. Because pump calls `destroy()` rather than `destroy(err)`. Is this by design?

Additionally, if you do add a error callback to pump [here](https://github.com/mcollina/cloneable-readable/blob/master/index.js#L46):

```js
function clonePiped (that) {
  if (--that._clonesCount === 0) {
    pump(that._original, that, function (err) {
      if (err) console.log(err)
    })
    that._original = undefined
  }
}
```

Then the tests reveal a few `[Error: stream.push() after EOF]`.

### PR DESCRIPTION
**Pull request by vweevers**
Implements:

1. Clone is destroyed or errors -> nothing happens to the other clones, or the Cloneable
2. Cloneable (or the cloned) errors -> all clones error
3. Cloneable (or the cloned) is destroyed -> all clones are destroyed

Except for:

> All clones are destroyed -> the Cloneable gets destroyed as well

 @mcollina what's your reasoning? If the clones are destroyed, shouldn't the cloneable remain readable itself?

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ test('basic passthrough in obj mode', function (t) {
   var read = false
   var source = from.obj(function (size, next) {
     if (read) {
-      this.push(null)
+      return this.push(null)
```
Comment (vweevers) [inline test.js]: I don't understand why, but without this, a `push after EOF` error occurs.

File: test.js [hunk 2]
```diff
@@ -121,7 +121,7 @@ test('multiple clone in object mode', function (t) {
...
```
Comment (vweevers) [inline test.js]: Same here.

File: test.js (hunk 1 above)
Comment (mcollina) [inline test.js]: This is the correct way to do things anyway.

File: index.js [hunk 3]
```diff
@@ -63,10 +73,12 @@ function Clone (parent, opts) {
   Ctor.call(this, opts)
 
   this.on('newListener', onDataClone)
+
+  forwardDestroy(this.parent, this)
 }
 
 function onDataClone (event, listener) {
-  if (event === 'data' || event === 'readable') {
+  if (event === 'data' || event === 'readable' || event === 'close') {
```
Comment (mcollina) [inline index.js]: Good spot. A comment on this would be really nice.

**Comment by mcollina** [comment]
> > All clones are destroyed -> the Cloneable gets destroyed as well
> @mcollina what's your reasoning? If the clones are destroyed, shouldn't the cloneable remain readable itself?

You are right. It's ok. There are a couple of nits.

Would you like to help maintaining this module?

**Comment by vweevers** [comment]
Added a comment.

> Would you like to help maintaining this module?

I'd be glad to.

File: index.js [hunk 4]
```diff
@@ -38,12 +39,21 @@ Cloneable.prototype.clone = function () {
...
+  return this.pipe(new Clone(this))
+}
+
+function forwardDestroy (src, dest) {
+  src.on('error', destroy)
+  src.on('close', destroy)
+
+  function destroy (err) {
+    dest.destroy(err)
+  }
```
Comment (mcollina) [inline index.js]: we should use https://github.com/mafintosh/end-of-stream to check that the stream errors

Comment (vweevers) [inline index.js]: First thing I tried. But it results in premature close errors, because when one stream (either the source or cloneable) emits `end`, the other (the cloneable or clone, respectively) might not be fully consumed yet - so it's unsafe to call `destroy` on it.

Comment (vweevers) [inline index.js]: Hmm, the same is true if the source emits `close` (without an error). OK, so we need a slightly smarter solution

Comment (vweevers) [inline index.js]: This works, but feels hacky:

```js
eos(src, { writable: false }, function (err) {
  if (/premature close/.test(err)) dest.destroy()
  else if (err) dest.destroy(err)
})
```

This way, we interpret a premature close - meaning a `close` event was emitted before `end` - as the source having been destroyed.

**Comment by mcollina** [comment]
Ok, I'm not 100% convinced, but we should better try this in the wild, and maybe port some bits from , are you ok with this, or there is more you wish to add?

**Comment by vweevers** [comment]
I'm a little bit confused by Github's review feature. Do you want to do this: https://github.com/mcollina/cloneable-readable/pull/2#r79286272? Sorry if it wasn't clear: I did not commit that bit yet.

File: index.js (hunk 4 above)
Comment (mcollina) [inline index.js]: No, the current code is fine, thanks for explaining your reasoning.

**Comment by mcollina** [comment]
@vweevers no need.

**Comment by vweevers** [comment]
Great. I'm OK with it 👍.

**Comment by mcollina** [comment]
Thanks!
